name: Continuous Integration
on: push

jobs:
  code-quality:
    name: Run code quality checks on PHP 7.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: msgpack, igbinary
      - name: Install Relay
        run: |
          curl -L "https://cachewerk.s3.amazonaws.com/relay/v0.5.0/relay-v0.5.0-php7.4-debian-x86-64.tar.gz" | tar xz
          cd relay-v0.5.0-php7.4-debian-x86-64
          sudo cp relay.ini $(php-config --ini-dir)
          sudo cp relay-pkg.so $(php-config --extension-dir)/relay.so
          sudo sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" $(php-config --extension-dir)/relay.so
      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist
      - name: Run code quality checks
        run: vendor/bin/grumphp run --testsuite=code_quality
  php-test:
    name: Run tests on ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    needs: code-quality
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: msgpack, igbinary
      - name: Install Relay
        if: 7.4 == matrix.php-versions || 8.0 == matrix.php-versions
        run: |
          curl -L "https://cachewerk.s3.amazonaws.com/relay/v0.5.0/relay-v0.5.0-php${{ matrix.php-versions }}-debian-x86-64.tar.gz" | tar xz
          cd relay-v0.5.0-php${{ matrix.php-versions }}-debian-x86-64
          sudo cp relay.ini $(php-config --ini-dir)
          sudo cp relay-pkg.so $(php-config --extension-dir)/relay.so
          sudo sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" $(php-config --extension-dir)/relay.so
      - name: Remove GrumPHP
        run: composer remove --dev phpro/grumphp
      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist
      - name: Install WordPress
        run: .github/workflows/install-wp.sh
      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit
      - name: Run integration tests
        env:
          AWS_TEST_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_ACCESS_KEY_ID }}
          AWS_TEST_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}
        run: vendor/bin/phpunit --testsuite integration
